server:
  port: 9002

spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.15:1433;databaseName=TESTDG
    username: sa
    password: giorselect,#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver





